global:
  scrape_interval: 5s # LÃª a API a cada 5 segundos

scrape_configs:
  - job_name: "fastapi_modelo"
    static_configs:
      - targets: ["host.docker.internal:8000"]
  - job_name: "machine_resources"
    static_configs:
      - targets: ["node-exporter:9100"]
